### ISSUE TITLE
Update the `api.yaml` configuration file with the new `upload_configuration` section and limits option

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh-chef#154]
| |
| - |
| **Target version** |
| 4.4 |

This issue is part of the epic issue https://github.com/wazuh/wazuh/issues/14140.

In the issue https://github.com/wazuh/wazuh/issues/13572, a new API configuration block was created to wrap all the possible configuration limitations through the API. In addition, some options have changed:

- The `remote_commands` will now be enabled or not using the key `allow` instead of `enabled`.
- In addition to the `remote_commands`, we now have a `limits` section.
- As before, the field `allow` will be a boolean.

This is the current block with its default values: 

```yaml
upload_configuration:
  remote_commands:
    localfile:
      allow: True
      exceptions: []
    wodle_command:
      allow: True
      exceptions: []
  limits:
    eps:
      allow: True
```

We should review this repository, update the remote commands and include the new API configuration parameters in the configuration file:

https://github.com/wazuh/wazuh-chef/blob/9e2ef3c39cd70cc5ad026a2268a1973920734677/cookbooks/wazuh_manager/templates/default/api.yaml.erb#L1-L49

Consider adding more changes in case they are needed.
